export const AppIcons = {
  applogo: require('../assets/icons/ratus_logo.png'),
  email: require('../assets/icons/email.png'),
  password: require('../assets/icons/password.png'),
  showPass: require('../assets/icons/showPass.png'),
  hidePass: require('../assets/icons/hidePass.png'),
  google: require('../assets/icons/google.png'),
  apple: require('../assets/icons/apple.png'),
  backArrow: require('../assets/icons/back_arrow.png'),
  rightArrow: require('../assets/icons/rightArrow.png'),
  user: require('../assets/icons/user.png'),
  home: require('../assets/icons/home.png'),
  location: require('../assets/icons/location.png'),
  mapLocation: require('../assets/icons/map_location.png'),
  notifications: require('../assets/icons/notifications.png'),
  search: require('../assets/icons/search.png'),
  bell: require('../assets/icons/bell.png'),
  edit: require('../assets/icons/edit.png'),
  language: require('../assets/icons/language.png'),
  lock: require('../assets/icons/lock.png'),
  help: require('../assets/icons/help.png'),
  invite: require('../assets/icons/invite.png'),
  delete: require('../assets/icons/delete.png'),
  logout: require('../assets/icons/logout.png'),
  next: require('../assets/icons/next.png'),
  circleAdd: require('../assets/icons/circlr_add.png'),
  circleTick: require('../assets/icons/circle_tick.png'),
  greenTick: require('../assets/icons/green_tick.png'),
  list: require('../assets/icons/list.png'),

};
